acompanhantes:
    path:     /
    defaults: { _controller: "EventFormBundle:Acompanhantes:index" }

acompanhantes_show:
    path:     /{id}/show
    defaults: { _controller: "EventFormBundle:Acompanhantes:show" }

acompanhantes_new:
    path:     /new
    defaults: { _controller: "EventFormBundle:Acompanhantes:new" }

acompanhantes_create:
    path:     /create
    defaults: { _controller: "EventFormBundle:Acompanhantes:create" }
    requirements: { _method: post }

acompanhantes_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventFormBundle:Acompanhantes:edit" }

acompanhantes_update:
    path:     /{id}/update
    defaults: { _controller: "EventFormBundle:Acompanhantes:update" }
    requirements: { _method: post|put }

acompanhantes_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventFormBundle:Acompanhantes:delete" }
    requirements: { _method: post|delete }
