periodo:
    path:     /
    defaults: { _controller: "EventFormBundle:Periodo:index" }

periodo_show:
    path:     /{id}/show
    defaults: { _controller: "EventFormBundle:Periodo:show" }

periodo_new:
    path:     /new
    defaults: { _controller: "EventFormBundle:Periodo:new" }

periodo_create:
    path:     /create
    defaults: { _controller: "EventFormBundle:Periodo:create" }
    requirements: { _method: post }

periodo_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventFormBundle:Periodo:edit" }

periodo_update:
    path:     /{id}/update
    defaults: { _controller: "EventFormBundle:Periodo:update" }
    requirements: { _method: post|put }

periodo_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventFormBundle:Periodo:delete" }
    requirements: { _method: post|delete }
