<?php

namespace EventWeb\EventFormBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodoDeInscricaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoDeInscricaoRepository extends EntityRepository
{
}
