<?php

namespace EventWeb\EventFormBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SistemaDeSociosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemaDeSociosRepository extends EntityRepository
{
}
